CREATE TABLE IF NOT EXISTS market_data.company_profile (
symbol VARCHAR(20) PRIMARY KEY,
short_name TEXT,
long_name TEXT,
quote_type TEXT,
exchange TEXT,
currency TEXT,
website TEXT,
sector TEXT,
industry TEXT,
country TEXT,
city TEXT,
state TEXT,
full_time_employees BIGINT,
long_business_summary TEXT,
market_cap NUMERIC(20,0),
enterprise_value NUMERIC(20,0),
total_revenue NUMERIC(20,0),
ebitda NUMERIC(20,0),
revenue_growth NUMERIC(12,6),
gross_margins NUMERIC(12,6),
operating_margins NUMERIC(12,6),
profit_margins NUMERIC(12,6),
free_cashflow NUMERIC(20,0),
trailing_pe NUMERIC(14,6),
forward_pe NUMERIC(14,6),
peg_ratio NUMERIC(14,6),
price_to_book NUMERIC(14,6),
trailing_eps NUMERIC(14,6),
forward_eps NUMERIC(14,6),
return_on_equity NUMERIC(14,6),
return_on_assets NUMERIC(14,6),
debt_to_equity NUMERIC(14,6),
current_ratio NUMERIC(14,6),
quick_ratio NUMERIC(14,6),
dividend_rate NUMERIC(14,6),
dividend_yield NUMERIC(14,6),
payout_ratio NUMERIC(14,6),
ex_dividend_date TIMESTAMPTZ,
beta NUMERIC(14,6),
shares_outstanding NUMERIC(20,0),
average_volume NUMERIC(20,0),
fifty_two_week_high NUMERIC(14,6),
fifty_two_week_low NUMERIC(14,6),
fifty_day_average NUMERIC(14,6),
two_hundred_day_average NUMERIC(14,6),
source_created_at TIMESTAMPTZ,
loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS market_data.financials(
    symbol VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    tax_effect_of_unusual_items NUMERIC(20,0),
    tax_rate_for_calcs NUMERIC(18,6),
    normalized_ebitda NUMERIC(20,0),
    net_income_from_continuing_operation_net_minority_interest NUMERIC(20,0),
    reconciled_depreciation NUMERIC(20,0),
    reconciled_cost_of_revenue NUMERIC(20,0),
    ebitda NUMERIC(20,0),
    ebit NUMERIC(20,0),
    net_interest_income NUMERIC(20,0),
    interest_expense NUMERIC(20,0),
    interest_income NUMERIC(20,0),
    normalized_income NUMERIC(20,0),
    net_income_from_continuing_and_discontinued_operation NUMERIC(20,0),
    total_expenses NUMERIC(20,0),
    total_operating_income_as_reported NUMERIC(20,0),
    diluted_average_shares NUMERIC(20,0),
    basic_average_shares NUMERIC(20,0),
    diluted_eps NUMERIC(18,6),
    basic_eps NUMERIC(18,6),
    diluted_ni_availto_com_stockholders NUMERIC(20,0),
    net_income_common_stockholders NUMERIC(20,0),
    net_income NUMERIC(20,0),
    net_income_including_noncontrolling_interests NUMERIC(20,0),
    net_income_continuous_operations NUMERIC(20,0),
    tax_provision NUMERIC(20,0),
    pretax_income NUMERIC(20,0),
    other_income_expense NUMERIC(20,0),
    other_non_operating_income_expenses NUMERIC(20,0),
    net_non_operating_interest_income_expense NUMERIC(20,0),
    interest_expense_non_operating NUMERIC(20,0),
    interest_income_non_operating NUMERIC(20,0),
    operating_income NUMERIC(20,0),
    operating_expense NUMERIC(20,0),
    research_and_development NUMERIC(20,0),
    selling_general_and_administration NUMERIC(20,0),
    gross_profit NUMERIC(20,0),
    cost_of_revenue NUMERIC(20,0),
    total_revenue NUMERIC(20,0),
    operating_revenue NUMERIC(20,0),
    PRIMARY KEY (symbol, year)

);

CREATE TABLE IF NOT EXISTS market_data.balance_sheet(
    symbol VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    treasury_shares_number NUMERIC(20,0),
    ordinary_shares_number NUMERIC(20,0),
    share_issued NUMERIC(20,0),
    net_debt NUMERIC(20,0),
    total_debt NUMERIC(20,0),
    tangible_book_value NUMERIC(20,0),
    invested_capital NUMERIC(20,0),
    working_capital NUMERIC(20,0),
    net_tangible_assets NUMERIC(20,0),
    capital_lease_obligations NUMERIC(20,0),
    common_stock_equity NUMERIC(20,0),
    total_capitalization NUMERIC(20,0),
    total_equity_gross_minority_interest NUMERIC(20,0),
    stockholders_equity NUMERIC(20,0),
    gains_losses_not_affecting_retained_earnings NUMERIC(20,0),
    other_equity_adjustments NUMERIC(20,0),
    retained_earnings NUMERIC(20,0),
    capital_stock NUMERIC(20,0),
    common_stock NUMERIC(20,0),
    total_liabilities_net_minority_interest NUMERIC(20,0),
    total_non_current_liabilities_net_minority_interest NUMERIC(20,0),
    other_non_current_liabilities NUMERIC(20,0),
    tradeand_other_payables_non_current NUMERIC(20,0),
    long_term_debt_and_capital_lease_obligation NUMERIC(20,0),
    long_term_capital_lease_obligation NUMERIC(20,0),
    long_term_debt NUMERIC(20,0),
    current_liabilities NUMERIC(20,0),
    other_current_liabilities NUMERIC(20,0),
    current_deferred_liabilities NUMERIC(20,0),
    current_deferred_revenue NUMERIC(20,0),
    current_debt_and_capital_lease_obligation NUMERIC(20,0),
    current_capital_lease_obligation NUMERIC(20,0),
    current_debt NUMERIC(20,0),
    other_current_borrowings NUMERIC(20,0),
    commercial_paper NUMERIC(20,0),
    payables_and_accrued_expenses NUMERIC(20,0),
    current_accrued_expenses NUMERIC(20,0),
    payables NUMERIC(20,0),
    total_tax_payable NUMERIC(20,0),
    income_tax_payable NUMERIC(20,0),
    accounts_payable NUMERIC(20,0),
    total_assets NUMERIC(20,0),
    total_non_current_assets NUMERIC(20,0),
    other_non_current_assets NUMERIC(20,0),
    non_current_deferred_assets NUMERIC(20,0),
    non_current_deferred_taxes_assets NUMERIC(20,0),
    investments_and_advances NUMERIC(20,0),
    other_investments NUMERIC(20,0),
    investmentin_financial_assets NUMERIC(20,0),
    available_for_sale_securities NUMERIC(20,0),
    net_ppe NUMERIC(20,0),
    accumulated_depreciation NUMERIC(20,0),
    gross_ppe NUMERIC(20,0),
    leases NUMERIC(20,0),
    other_properties NUMERIC(20,0),
    machinery_furniture_equipment NUMERIC(20,0),
    land_and_improvements NUMERIC(20,0),
    properties NUMERIC(20,0),
    current_assets NUMERIC(20,0),
    other_current_assets NUMERIC(20,0),
    inventory NUMERIC(20,0),
    receivables NUMERIC(20,0),
    other_receivables NUMERIC(20,0),
    accounts_receivable NUMERIC(20,0),
    cash_cash_equivalents_and_short_term_investments NUMERIC(20,0),
    other_short_term_investments NUMERIC(20,0),
    cash_and_cash_equivalents NUMERIC(20,0),
    cash_equivalents NUMERIC(20,0),
    cash_financial NUMERIC(20,0),
    PRIMARY KEY (symbol, year)
);

CREATE TABLE IF NOT EXISTS market_data.cash_flow(
    symbol VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    free_cash_flow NUMERIC(20,0),
    repurchase_of_capital_stock NUMERIC(20,0),
    repayment_of_debt NUMERIC(20,0),
    issuance_of_debt NUMERIC(20,0),
    issuance_of_capital_stock NUMERIC(20,0),
    capital_expenditure NUMERIC(20,0),
    interest_paid_supplemental_data NUMERIC(20,0),
    income_tax_paid_supplemental_data NUMERIC(20,0),
    end_cash_position NUMERIC(20,0),
    beginning_cash_position NUMERIC(20,0),
    changes_in_cash NUMERIC(20,0),
    financing_cash_flow NUMERIC(20,0),
    cash_flow_from_continuing_financing_activities NUMERIC(20,0),
    net_other_financing_charges NUMERIC(20,0),
    cash_dividends_paid NUMERIC(20,0),
    common_stock_dividend_paid NUMERIC(20,0),
    net_common_stock_issuance NUMERIC(20,0),
    common_stock_payments NUMERIC(20,0),
    common_stock_issuance NUMERIC(20,0),
    net_issuance_payments_of_debt NUMERIC(20,0),
    net_short_term_debt_issuance NUMERIC(20,0),
    net_long_term_debt_issuance NUMERIC(20,0),
    long_term_debt_payments NUMERIC(20,0),
    long_term_debt_issuance NUMERIC(20,0),
    investing_cash_flow NUMERIC(20,0),
    cash_flow_from_continuing_investing_activities NUMERIC(20,0),
    net_other_investing_changes NUMERIC(20,0),
    net_investment_purchase_and_sale NUMERIC(20,0),
    sale_of_investment NUMERIC(20,0),
    purchase_of_investment NUMERIC(20,0),
    net_business_purchase_and_sale NUMERIC(20,0),
    purchase_of_business NUMERIC(20,0),
    net_ppe_purchase_and_sale NUMERIC(20,0),
    purchase_of_ppe NUMERIC(20,0),
    operating_cash_flow NUMERIC(20,0),
    cash_flow_from_continuing_operating_activities NUMERIC(20,0),
    change_in_working_capital NUMERIC(20,0),
    change_in_other_working_capital NUMERIC(20,0),
    change_in_other_current_liabilities NUMERIC(20,0),
    change_in_other_current_assets NUMERIC(20,0),
    change_in_payables_and_accrued_expense NUMERIC(20,0),
    change_in_payable NUMERIC(20,0),
    change_in_account_payable NUMERIC(20,0),
    change_in_inventory NUMERIC(20,0),
    change_in_receivables NUMERIC(20,0),
    changes_in_account_receivables NUMERIC(20,0),
    other_non_cash_items NUMERIC(20,0),
    stock_based_compensation NUMERIC(20,0),
    deferred_tax NUMERIC(20,0),
    deferred_income_tax NUMERIC(20,0),
    depreciation_amortization_depletion NUMERIC(20,0),
    depreciation_and_amortization NUMERIC(20,0),
    net_income_from_continuing_operations NUMERIC(20,0),
    PRIMARY KEY (symbol, year)
);

CREATE INDEX IF NOT EXISTS idx_industry ON market_data.company_profile(industry);

CREATE INDEX IF NOT EXISTS idx_symbol_industry on market_data.company_profile(symbol, industry);

CREATE INDEX IF NOT EXISTS idx_symbol_sector on market_data.company_profile(symbol,sector);