WITH latest_info AS (
SELECT x.*
FROM (
SELECT
i.*,
ROW_NUMBER() OVER (PARTITION BY i.symbol ORDER BY i.created_at DESC NULLS LAST) AS rn
FROM market_data.info i
) x
WHERE x.rn = 1
)
INSERT INTO market_data.company_profile (
symbol, short_name, long_name, quote_type, exchange, currency, website,
sector, industry, country, city, state, full_time_employees, long_business_summary,
market_cap, enterprise_value, total_revenue, ebitda, revenue_growth, gross_margins,
operating_margins, profit_margins, free_cashflow, trailing_pe, forward_pe, peg_ratio,
price_to_book, trailing_eps, forward_eps, return_on_equity, return_on_assets, debt_to_equity,
current_ratio, quick_ratio, dividend_rate, dividend_yield, payout_ratio, ex_dividend_date,
beta, shares_outstanding, average_volume, fifty_two_week_high, fifty_two_week_low,
fifty_day_average, two_hundred_day_average, source_created_at
)
SELECT
li.symbol,
li.jsondump->>'shortName',
li.jsondump->>'longName',
li.jsondump->>'quoteType',
li.jsondump->>'exchange',
li.jsondump->>'currency',
li.jsondump->>'website',
li.jsondump->>'sector',
li.jsondump->>'industry',
li.jsondump->>'country',
li.jsondump->>'city',
li.jsondump->>'state',
NULLIF(li.jsondump->>'fullTimeEmployees','')::BIGINT,
li.jsondump->>'longBusinessSummary',
NULLIF(li.jsondump->>'marketCap','')::NUMERIC,
NULLIF(li.jsondump->>'enterpriseValue','')::NUMERIC,
NULLIF(li.jsondump->>'totalRevenue','')::NUMERIC,
NULLIF(li.jsondump->>'ebitda','')::NUMERIC,
NULLIF(li.jsondump->>'revenueGrowth','')::NUMERIC,
NULLIF(li.jsondump->>'grossMargins','')::NUMERIC,
NULLIF(li.jsondump->>'operatingMargins','')::NUMERIC,
NULLIF(li.jsondump->>'profitMargins','')::NUMERIC,
NULLIF(li.jsondump->>'freeCashflow','')::NUMERIC,
NULLIF(li.jsondump->>'trailingPE','')::NUMERIC,
NULLIF(li.jsondump->>'forwardPE','')::NUMERIC,
NULLIF(li.jsondump->>'pegRatio','')::NUMERIC,
NULLIF(li.jsondump->>'priceToBook','')::NUMERIC,
NULLIF(li.jsondump->>'trailingEps','')::NUMERIC,
NULLIF(li.jsondump->>'forwardEps','')::NUMERIC,
NULLIF(li.jsondump->>'returnOnEquity','')::NUMERIC,
NULLIF(li.jsondump->>'returnOnAssets','')::NUMERIC,
NULLIF(li.jsondump->>'debtToEquity','')::NUMERIC,
NULLIF(li.jsondump->>'currentRatio','')::NUMERIC,
NULLIF(li.jsondump->>'quickRatio','')::NUMERIC,
NULLIF(li.jsondump->>'dividendRate','')::NUMERIC,
NULLIF(li.jsondump->>'dividendYield','')::NUMERIC,
NULLIF(li.jsondump->>'payoutRatio','')::NUMERIC,
TO_TIMESTAMP(NULLIF(li.jsondump->>'exDividendDate','')::BIGINT),
NULLIF(li.jsondump->>'beta','')::NUMERIC,
NULLIF(li.jsondump->>'sharesOutstanding','')::NUMERIC,
NULLIF(li.jsondump->>'averageVolume','')::NUMERIC,
NULLIF(li.jsondump->>'fiftyTwoWeekHigh','')::NUMERIC,
NULLIF(li.jsondump->>'fiftyTwoWeekLow','')::NUMERIC,
NULLIF(li.jsondump->>'fiftyDayAverage','')::NUMERIC,
NULLIF(li.jsondump->>'twoHundredDayAverage','')::NUMERIC,
li.created_at
FROM latest_info li
ON CONFLICT (symbol) DO UPDATE SET
short_name = EXCLUDED.short_name,
long_name = EXCLUDED.long_name,
quote_type = EXCLUDED.quote_type,
exchange = EXCLUDED.exchange,
currency = EXCLUDED.currency,
website = EXCLUDED.website,
sector = EXCLUDED.sector,
industry = EXCLUDED.industry,
country = EXCLUDED.country,
city = EXCLUDED.city,
state = EXCLUDED.state,
full_time_employees = EXCLUDED.full_time_employees,
long_business_summary = EXCLUDED.long_business_summary,
market_cap = EXCLUDED.market_cap,
enterprise_value = EXCLUDED.enterprise_value,
total_revenue = EXCLUDED.total_revenue,
ebitda = EXCLUDED.ebitda,
revenue_growth = EXCLUDED.revenue_growth,
gross_margins = EXCLUDED.gross_margins,
operating_margins = EXCLUDED.operating_margins,
profit_margins = EXCLUDED.profit_margins,
free_cashflow = EXCLUDED.free_cashflow,
trailing_pe = EXCLUDED.trailing_pe,
forward_pe = EXCLUDED.forward_pe,
peg_ratio = EXCLUDED.peg_ratio,
price_to_book = EXCLUDED.price_to_book,
trailing_eps = EXCLUDED.trailing_eps,
forward_eps = EXCLUDED.forward_eps,
return_on_equity = EXCLUDED.return_on_equity,
return_on_assets = EXCLUDED.return_on_assets,
debt_to_equity = EXCLUDED.debt_to_equity,
current_ratio = EXCLUDED.current_ratio,
quick_ratio = EXCLUDED.quick_ratio,
dividend_rate = EXCLUDED.dividend_rate,
dividend_yield = EXCLUDED.dividend_yield,
payout_ratio = EXCLUDED.payout_ratio,
ex_dividend_date = EXCLUDED.ex_dividend_date,
beta = EXCLUDED.beta,
shares_outstanding = EXCLUDED.shares_outstanding,
average_volume = EXCLUDED.average_volume,
fifty_two_week_high = EXCLUDED.fifty_two_week_high,
fifty_two_week_low = EXCLUDED.fifty_two_week_low,
fifty_day_average = EXCLUDED.fifty_day_average,
two_hundred_day_average = EXCLUDED.two_hundred_day_average,
source_created_at = EXCLUDED.source_created_at,
loaded_at = NOW();