from api.core.database import Base
from sqlalchemy import String, Text, BigInteger, Numeric, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import JSONB
from typing import Dict
from datetime import datetime

class StockDataInfoStaging(Base):
    __tablename__ = "info"
    __table_args__ ={"schema":"market_data"}

    symbol: Mapped[str] = mapped_column(String(10),primary_key = True)
    jsondump : Mapped[Dict[str,str]] = mapped_column(JSONB)
    created_at : Mapped[datetime] = mapped_column(server_default =func.now())

class StockDataFinancialsStaging(Base):
    __tablename__ = "financials_staging"
    __table_args__ = {"schema":"market_data"}

    symbol: Mapped[str] = mapped_column(String(10),primary_key = True)
    jsondump : Mapped[Dict[str,str]] = mapped_column(JSONB)
    created_at : Mapped[datetime] = mapped_column(server_default =func.now())

class StockDataBalanceStaging(Base):
    __tablename__ = "balance_staging"
    __table_args__ = {"schema":"market_data"}

    symbol: Mapped[str] = mapped_column(String(10),primary_key = True)
    jsondump : Mapped[Dict[str,str]] = mapped_column(JSONB)
    created_at : Mapped[datetime] = mapped_column(server_default =func.now())

class StockDataCashStaging(Base):
    __tablename__ = "cash_staging"
    __table_args__ = {"schema":"market_data"}

    symbol: Mapped[str] = mapped_column(String(10),primary_key = True)
    jsondump : Mapped[Dict[str,str]] = mapped_column(JSONB)
    created_at : Mapped[datetime] = mapped_column(server_default =func.now())

class StockDataFinancials(Base):
    __tablename__ = "financials"
    __table_args__ = {"schema": "market_data"}

    symbol: Mapped[str] = mapped_column(String(20), primary_key=True)
    year: Mapped[int] = mapped_column(primary_key=True)
    tax_effect_of_unusual_items: Mapped[float | None] = mapped_column(Numeric(20, 0))
    tax_rate_for_calcs: Mapped[float | None] = mapped_column(Numeric(18, 6))
    normalized_ebitda: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_from_continuing_operation_net_minority_interest: Mapped[float | None] = mapped_column(Numeric(20, 0))
    reconciled_depreciation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    reconciled_cost_of_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))
    ebitda: Mapped[float | None] = mapped_column(Numeric(20, 0))
    ebit: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_interest_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    interest_expense: Mapped[float | None] = mapped_column(Numeric(20, 0))
    interest_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    normalized_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_from_continuing_and_discontinued_operation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_expenses: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_operating_income_as_reported: Mapped[float | None] = mapped_column(Numeric(20, 0))
    diluted_average_shares: Mapped[float | None] = mapped_column(Numeric(20, 0))
    basic_average_shares: Mapped[float | None] = mapped_column(Numeric(20, 0))
    diluted_eps: Mapped[float | None] = mapped_column(Numeric(18, 6))
    basic_eps: Mapped[float | None] = mapped_column(Numeric(18, 6))
    diluted_ni_availto_com_stockholders: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_common_stockholders: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_including_noncontrolling_interests: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_continuous_operations: Mapped[float | None] = mapped_column(Numeric(20, 0))
    tax_provision: Mapped[float | None] = mapped_column(Numeric(20, 0))
    pretax_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_income_expense: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_non_operating_income_expenses: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_non_operating_interest_income_expense: Mapped[float | None] = mapped_column(Numeric(20, 0))
    interest_expense_non_operating: Mapped[float | None] = mapped_column(Numeric(20, 0))
    interest_income_non_operating: Mapped[float | None] = mapped_column(Numeric(20, 0))
    operating_income: Mapped[float | None] = mapped_column(Numeric(20, 0))
    operating_expense: Mapped[float | None] = mapped_column(Numeric(20, 0))
    research_and_development: Mapped[float | None] = mapped_column(Numeric(20, 0))
    selling_general_and_administration: Mapped[float | None] = mapped_column(Numeric(20, 0))
    gross_profit: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cost_of_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))
    operating_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))

class StockDataBalance(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"schema": "market_data"}

    symbol: Mapped[str] = mapped_column(String(20), primary_key=True)
    year: Mapped[int] = mapped_column(primary_key=True)
    treasury_shares_number: Mapped[float | None] = mapped_column(Numeric(20, 0))
    ordinary_shares_number: Mapped[float | None] = mapped_column(Numeric(20, 0))
    share_issued: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    tangible_book_value: Mapped[float | None] = mapped_column(Numeric(20, 0))
    invested_capital: Mapped[float | None] = mapped_column(Numeric(20, 0))
    working_capital: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_tangible_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    capital_lease_obligations: Mapped[float | None] = mapped_column(Numeric(20, 0))
    common_stock_equity: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_capitalization: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_equity_gross_minority_interest: Mapped[float | None] = mapped_column(Numeric(20, 0))
    stockholders_equity: Mapped[float | None] = mapped_column(Numeric(20, 0))
    gains_losses_not_affecting_retained_earnings: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_equity_adjustments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    retained_earnings: Mapped[float | None] = mapped_column(Numeric(20, 0))
    capital_stock: Mapped[float | None] = mapped_column(Numeric(20, 0))
    common_stock: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_liabilities_net_minority_interest: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_non_current_liabilities_net_minority_interest: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_non_current_liabilities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    tradeand_other_payables_non_current: Mapped[float | None] = mapped_column(Numeric(20, 0))
    long_term_debt_and_capital_lease_obligation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    long_term_capital_lease_obligation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    long_term_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_liabilities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_current_liabilities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_deferred_liabilities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_deferred_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_debt_and_capital_lease_obligation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_capital_lease_obligation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_current_borrowings: Mapped[float | None] = mapped_column(Numeric(20, 0))
    commercial_paper: Mapped[float | None] = mapped_column(Numeric(20, 0))
    payables_and_accrued_expenses: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_accrued_expenses: Mapped[float | None] = mapped_column(Numeric(20, 0))
    payables: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_tax_payable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    income_tax_payable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    accounts_payable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_non_current_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_non_current_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    non_current_deferred_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    non_current_deferred_taxes_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    investments_and_advances: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_investments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    investmentin_financial_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    available_for_sale_securities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_ppe: Mapped[float | None] = mapped_column(Numeric(20, 0))
    accumulated_depreciation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    gross_ppe: Mapped[float | None] = mapped_column(Numeric(20, 0))
    leases: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_properties: Mapped[float | None] = mapped_column(Numeric(20, 0))
    machinery_furniture_equipment: Mapped[float | None] = mapped_column(Numeric(20, 0))
    land_and_improvements: Mapped[float | None] = mapped_column(Numeric(20, 0))
    properties: Mapped[float | None] = mapped_column(Numeric(20, 0))
    current_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_current_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    inventory: Mapped[float | None] = mapped_column(Numeric(20, 0))
    receivables: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_receivables: Mapped[float | None] = mapped_column(Numeric(20, 0))
    accounts_receivable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_cash_equivalents_and_short_term_investments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_short_term_investments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_and_cash_equivalents: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_equivalents: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_financial: Mapped[float | None] = mapped_column(Numeric(20, 0))

class StockDataCash(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"schema": "market_data"}

    symbol: Mapped[str] = mapped_column(String(20), primary_key=True)
    year: Mapped[int] = mapped_column(primary_key=True)
    free_cash_flow: Mapped[float | None] = mapped_column(Numeric(20, 0))
    repurchase_of_capital_stock: Mapped[float | None] = mapped_column(Numeric(20, 0))
    repayment_of_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    issuance_of_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    issuance_of_capital_stock: Mapped[float | None] = mapped_column(Numeric(20, 0))
    capital_expenditure: Mapped[float | None] = mapped_column(Numeric(20, 0))
    interest_paid_supplemental_data: Mapped[float | None] = mapped_column(Numeric(20, 0))
    income_tax_paid_supplemental_data: Mapped[float | None] = mapped_column(Numeric(20, 0))
    end_cash_position: Mapped[float | None] = mapped_column(Numeric(20, 0))
    beginning_cash_position: Mapped[float | None] = mapped_column(Numeric(20, 0))
    changes_in_cash: Mapped[float | None] = mapped_column(Numeric(20, 0))
    financing_cash_flow: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_flow_from_continuing_financing_activities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_other_financing_charges: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_dividends_paid: Mapped[float | None] = mapped_column(Numeric(20, 0))
    common_stock_dividend_paid: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_common_stock_issuance: Mapped[float | None] = mapped_column(Numeric(20, 0))
    common_stock_payments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    common_stock_issuance: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_issuance_payments_of_debt: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_short_term_debt_issuance: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_long_term_debt_issuance: Mapped[float | None] = mapped_column(Numeric(20, 0))
    long_term_debt_payments: Mapped[float | None] = mapped_column(Numeric(20, 0))
    long_term_debt_issuance: Mapped[float | None] = mapped_column(Numeric(20, 0))
    investing_cash_flow: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_flow_from_continuing_investing_activities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_other_investing_changes: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_investment_purchase_and_sale: Mapped[float | None] = mapped_column(Numeric(20, 0))
    sale_of_investment: Mapped[float | None] = mapped_column(Numeric(20, 0))
    purchase_of_investment: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_business_purchase_and_sale: Mapped[float | None] = mapped_column(Numeric(20, 0))
    purchase_of_business: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_ppe_purchase_and_sale: Mapped[float | None] = mapped_column(Numeric(20, 0))
    purchase_of_ppe: Mapped[float | None] = mapped_column(Numeric(20, 0))
    operating_cash_flow: Mapped[float | None] = mapped_column(Numeric(20, 0))
    cash_flow_from_continuing_operating_activities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_working_capital: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_other_working_capital: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_other_current_liabilities: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_other_current_assets: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_payables_and_accrued_expense: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_payable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_account_payable: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_inventory: Mapped[float | None] = mapped_column(Numeric(20, 0))
    change_in_receivables: Mapped[float | None] = mapped_column(Numeric(20, 0))
    changes_in_account_receivables: Mapped[float | None] = mapped_column(Numeric(20, 0))
    other_non_cash_items: Mapped[float | None] = mapped_column(Numeric(20, 0))
    stock_based_compensation: Mapped[float | None] = mapped_column(Numeric(20, 0))
    deferred_tax: Mapped[float | None] = mapped_column(Numeric(20, 0))
    deferred_income_tax: Mapped[float | None] = mapped_column(Numeric(20, 0))
    depreciation_amortization_depletion: Mapped[float | None] = mapped_column(Numeric(20, 0))
    depreciation_and_amortization: Mapped[float | None] = mapped_column(Numeric(20, 0))
    net_income_from_continuing_operations: Mapped[float | None] = mapped_column(Numeric(20, 0))
    
class StockDataCompanyProfile(Base):
    __tablename__ = "company_profile"
    __table_args__ = {"schema": "market_data"}

    symbol: Mapped[str] = mapped_column(String(20), primary_key=True)
    short_name: Mapped[str | None] = mapped_column(Text)
    long_name: Mapped[str | None] = mapped_column(Text)
    quote_type: Mapped[str | None] = mapped_column(Text)
    exchange: Mapped[str | None] = mapped_column(Text)
    currency: Mapped[str | None] = mapped_column(Text)
    website: Mapped[str | None] = mapped_column(Text)
    sector: Mapped[str | None] = mapped_column(Text)
    industry: Mapped[str | None] = mapped_column(Text)
    country: Mapped[str | None] = mapped_column(Text)
    city: Mapped[str | None] = mapped_column(Text)
    state: Mapped[str | None] = mapped_column(Text)
    full_time_employees: Mapped[int | None] = mapped_column(BigInteger)
    long_business_summary: Mapped[str | None] = mapped_column(Text)

    market_cap: Mapped[float | None] = mapped_column(Numeric(20, 0))
    enterprise_value: Mapped[float | None] = mapped_column(Numeric(20, 0))
    total_revenue: Mapped[float | None] = mapped_column(Numeric(20, 0))
    ebitda: Mapped[float | None] = mapped_column(Numeric(20, 0))

    revenue_growth: Mapped[float | None] = mapped_column(Numeric(12, 6))
    gross_margins: Mapped[float | None] = mapped_column(Numeric(12, 6))
    operating_margins: Mapped[float | None] = mapped_column(Numeric(12, 6))
    profit_margins: Mapped[float | None] = mapped_column(Numeric(12, 6))

    free_cashflow: Mapped[float | None] = mapped_column(Numeric(20, 0))
    trailing_pe: Mapped[float | None] = mapped_column(Numeric(14, 6))
    forward_pe: Mapped[float | None] = mapped_column(Numeric(14, 6))
    peg_ratio: Mapped[float | None] = mapped_column(Numeric(14, 6))
    price_to_book: Mapped[float | None] = mapped_column(Numeric(14, 6))
    trailing_eps: Mapped[float | None] = mapped_column(Numeric(14, 6))
    forward_eps: Mapped[float | None] = mapped_column(Numeric(14, 6))
    return_on_equity: Mapped[float | None] = mapped_column(Numeric(14, 6))
    return_on_assets: Mapped[float | None] = mapped_column(Numeric(14, 6))
    debt_to_equity: Mapped[float | None] = mapped_column(Numeric(14, 6))
    current_ratio: Mapped[float | None] = mapped_column(Numeric(14, 6))
    quick_ratio: Mapped[float | None] = mapped_column(Numeric(14, 6))
    dividend_rate: Mapped[float | None] = mapped_column(Numeric(14, 6))
    dividend_yield: Mapped[float | None] = mapped_column(Numeric(14, 6))
    payout_ratio: Mapped[float | None] = mapped_column(Numeric(14, 6))

    ex_dividend_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    beta: Mapped[float | None] = mapped_column(Numeric(14, 6))
    shares_outstanding: Mapped[float | None] = mapped_column(Numeric(20, 0))
    average_volume: Mapped[float | None] = mapped_column(Numeric(20, 0))
    fifty_two_week_high: Mapped[float | None] = mapped_column(Numeric(14, 6))
    fifty_two_week_low: Mapped[float | None] = mapped_column(Numeric(14, 6))
    fifty_day_average: Mapped[float | None] = mapped_column(Numeric(14, 6))
    two_hundred_day_average: Mapped[float | None] = mapped_column(Numeric(14, 6))

    source_created_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    loaded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

