import { useState } from "react"
import type { Dispatch, SetStateAction } from "react"

type LessonStep = {
  id: string
  term: string
  short: string
  explanation: string
  example: string
}

const CashFlowStatement = ({ setStepFundamental }: { setStepFundamental: Dispatch<SetStateAction<number>> }) => {
  const [currentStep, setCurrentStep] = useState<number>(0)

  const steps: LessonStep[] = [
    {
      id: "operatingCashFlow",
      term: "Operating Cash Flow",
      short: "Cash generated by the core business.",
      explanation:
        "Operating cash flow shows whether everyday operations produce cash after working-capital movements.",
      example: "2025 operating cash flow is 8.7."
    },
    {
      id: "investingCashFlow",
      term: "Investing Cash Flow",
      short: "Cash spent on or received from investments.",
      explanation:
        "Investing cash flow is often negative when the company invests in long-term growth.",
      example: "2025 investing cash flow is -2.8."
    },
    {
      id: "financingCashFlow",
      term: "Financing Cash Flow",
      short: "Cash from debt, equity, and shareholder distributions.",
      explanation:
        "Financing cash flow reflects how the company funds itself and returns capital.",
      example: "2025 financing cash flow is -2.1."
    },
    {
      id: "capitalExpenditure",
      term: "Capital Expenditure (CapEx)",
      short: "Cash spent on long-term assets and platform infrastructure.",
      explanation:
        "CapEx is the cash outflow for long-lived investments like warehouses, technology infrastructure, and equipment. It is required for scaling but reduces short-term free cash generation.",
      example: "2025 CapEx is -2.6."
    },
    {
      id: "freeCashFlow",
      term: "Free Cash Flow",
      short: "Cash left after operations and essential reinvestment.",
      explanation:
        "Free cash flow measures how much cash remains after funding operations and capital investments. A steadily positive FCF profile gives management flexibility for debt reduction, acquisitions, and shareholder returns.",
      example: "2025 Free Cash Flow = Operating Cash Flow - CapEx = 8.7 - 2.6 = 6.1."
    },
    {
      id: "netChangeCash",
      term: "Net Change in Cash",
      short: "Total yearly movement in cash.",
      explanation:
        "Net change in cash is operating + investing + financing cash flow.",
      example: "8.7 + (-2.8) + (-2.1) = +3.8 in 2025."
    },
    {
      id: "endingCash",
      term: "Ending Cash",
      short: "Cash balance at the end of the period.",
      explanation:
        "Ending cash equals beginning cash plus net change in cash and links to the balance sheet cash line.",
      example: "Ending cash is 16.2 in 2025."
    }
  ]

  const activeId = steps[currentStep].id

  const getRowClass = (id: string, emphasize = false) =>
    [
      "[&>td]:px-4",
      "[&>td]:py-3",
      "[&>td]:align-middle",
      "[&>td]:transition-colors",
      "[&>td:first-child]:rounded-l-lg",
      "[&>td:last-child]:rounded-r-lg",
      "[&>td:not(:first-child)]:text-right",
      emphasize ? "[&>td]:font-semibold" : "",
      activeId === id ? "[&>td]:bg-rose-100 [&>td]:text-rose-900" : "[&>td]:bg-white [&>td]:text-slate-800"
    ].join(" ")

  return (
    <section className="w-full max-w-6xl mx-auto px-4 py-8 md:px-6">
      <div className="mb-6">
        <h2 className="text-3xl font-semibold tracking-tight text-slate-900">Cash Flow Statement Tutorial</h2>
        <p className="mt-2 text-sm text-slate-600">Mercado Libre annual data (2023-2025), values in USD billions.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1.2fr)_minmax(300px,0.8fr)]">
        <div className="rounded-2xl border border-slate-200 bg-slate-100/70 p-3 shadow-sm md:p-4">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[640px] border-separate border-spacing-y-1">
              <thead>
                <tr className="[&>th]:px-4 [&>th]:pb-2 [&>th]:text-xs [&>th]:font-semibold [&>th]:uppercase [&>th]:tracking-wide [&>th]:text-slate-500">
                  <th className="text-left">Line Item</th>
                  <th className="text-right">2023</th>
                  <th className="text-right">2024</th>
                  <th className="text-right">2025</th>
                </tr>
              </thead>
              <tbody>
                <tr className={getRowClass("operatingCashFlow")}> 
                  <td>Operating Cash Flow</td>
                  <td>4.8</td>
                  <td>6.1</td>
                  <td>8.7</td>
                </tr>
                <tr className={getRowClass("investingCashFlow")}> 
                  <td>Investing Cash Flow</td>
                  <td>-1.7</td>
                  <td>-2.3</td>
                  <td>-2.8</td>
                </tr>
                <tr className={getRowClass("financingCashFlow")}> 
                  <td>Financing Cash Flow</td>
                  <td>-1.2</td>
                  <td>-1.2</td>
                  <td>-2.1</td>
                </tr>
                <tr className={getRowClass("capitalExpenditure")}> 
                  <td>Capital Expenditure (CapEx)</td>
                  <td>-1.4</td>
                  <td>-1.9</td>
                  <td>-2.6</td>
                </tr>
                <tr className={getRowClass("freeCashFlow", true)}>
                  <td>Free Cash Flow</td>
                  <td>3.4</td>
                  <td>4.2</td>
                  <td>6.1</td>
                </tr>
                <tr className={getRowClass("netChangeCash", true)}>
                  <td>Net Change in Cash</td>
                  <td>1.9</td>
                  <td>2.6</td>
                  <td>3.8</td>
                </tr>
                <tr className={getRowClass("endingCash", true)}>
                  <td>Ending Cash</td>
                  <td>9.8</td>
                  <td>12.4</td>
                  <td>16.2</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <aside className="rounded-2xl border border-slate-900 bg-slate-900 p-5 text-slate-100 shadow-lg lg:sticky lg:top-24 lg:h-fit">
          <div className="mb-3 inline-flex rounded-full bg-slate-700 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-slate-200">
            Step {currentStep + 1} of {steps.length}
          </div>
          <h3 className="text-2xl font-semibold leading-tight">{steps[currentStep].term}</h3>
          <p className="mt-2 text-sm text-slate-300">{steps[currentStep].short}</p>

          <div className="mt-4 rounded-xl border border-slate-700 bg-slate-800/70 p-3 text-sm leading-relaxed text-slate-200">
            {steps[currentStep].explanation}
          </div>

          <div className="mt-4 rounded-xl bg-rose-500/15 p-3">
            <div className="text-xs font-semibold uppercase tracking-wide text-rose-200">Example</div>
            <p className="mt-1 text-sm text-rose-100">{steps[currentStep].example}</p>
          </div>

          <div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-2">
            <button
              onClick={() => setCurrentStep((prev) => prev - 1)}
              disabled={currentStep === 0}
              className="rounded-lg border border-slate-500 bg-slate-700 px-3 py-2 text-sm font-medium text-slate-100 transition hover:bg-slate-600 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Previous
            </button>
            <div className="text-sm tabular-nums text-slate-300">
              {currentStep + 1}/{steps.length}
            </div>
            <button
              onClick={() => setCurrentStep((prev) => prev + 1)}
              disabled={currentStep >= steps.length - 1}
              className="rounded-lg border border-slate-500 bg-slate-700 px-3 py-2 text-sm font-medium text-slate-100 transition hover:bg-slate-600 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Next
            </button>
          </div>

          <button
            onClick={() => setStepFundamental(1)}
            className="w-full mt-5 rounded-lg border border-slate-500 bg-slate-700 px-3 py-2 text-sm font-medium text-slate-100 transition hover:bg-slate-600"
          >
            Back to Balance Sheet
          </button>
          <button
            onClick={() => setStepFundamental(3)}
            className="w-full mt-2 rounded-lg border border-rose-300/70 bg-rose-500/90 px-3 py-2 text-sm font-semibold text-white transition hover:bg-rose-500"
          >
            Go to Financial Ratios
          </button>
        </aside>
      </div>
    </section>
  )
}

export default CashFlowStatement
